# -*- coding: utf-8 -*-
"""Bot.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Zu7QMtTKZdWC65mJD2J3QzBtObb_O-cj
"""

def usuario(): # Define la función llamada usuario
    nombre = input("Por favor ingrese su nombre: ")# Genera un cuadro de texto para que el usuario responda una pregunta.
    print(f"Hola, {nombre}! Encantado de conocerte.") # Genera un texto especifico "Hola, Encantado de conocerte" y la f define la variable del nombre, por eso es que se cambia el nombre acorde a lo ingresado.
    print() # Da un espacio.
    print(f"¿En qué te puedo ayudar, {nombre}?") # Genera un texto especifico y la f permite el cambio de texto acorde a lo ingresado en el nombre.


usuario() # Sirve para correr el programa.